// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: url-shortner/v1/url-shortner.proto

package urlshortnerapiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// URLShortnerServiceClient is the client API for URLShortnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type URLShortnerServiceClient interface {
	ShortURL(ctx context.Context, in *ShortURLRequest, opts ...grpc.CallOption) (*ShortURLResponse, error)
}

type uRLShortnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewURLShortnerServiceClient(cc grpc.ClientConnInterface) URLShortnerServiceClient {
	return &uRLShortnerServiceClient{cc}
}

func (c *uRLShortnerServiceClient) ShortURL(ctx context.Context, in *ShortURLRequest, opts ...grpc.CallOption) (*ShortURLResponse, error) {
	out := new(ShortURLResponse)
	err := c.cc.Invoke(ctx, "/urlshortnerapiv1.URLShortnerService/ShortURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// URLShortnerServiceServer is the server API for URLShortnerService service.
// All implementations must embed UnimplementedURLShortnerServiceServer
// for forward compatibility
type URLShortnerServiceServer interface {
	ShortURL(context.Context, *ShortURLRequest) (*ShortURLResponse, error)
	mustEmbedUnimplementedURLShortnerServiceServer()
}

// UnimplementedURLShortnerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedURLShortnerServiceServer struct {
}

func (UnimplementedURLShortnerServiceServer) ShortURL(context.Context, *ShortURLRequest) (*ShortURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShortURL not implemented")
}
func (UnimplementedURLShortnerServiceServer) mustEmbedUnimplementedURLShortnerServiceServer() {}

// UnsafeURLShortnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to URLShortnerServiceServer will
// result in compilation errors.
type UnsafeURLShortnerServiceServer interface {
	mustEmbedUnimplementedURLShortnerServiceServer()
}

func RegisterURLShortnerServiceServer(s grpc.ServiceRegistrar, srv URLShortnerServiceServer) {
	s.RegisterService(&URLShortnerService_ServiceDesc, srv)
}

func _URLShortnerService_ShortURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortnerServiceServer).ShortURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlshortnerapiv1.URLShortnerService/ShortURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortnerServiceServer).ShortURL(ctx, req.(*ShortURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// URLShortnerService_ServiceDesc is the grpc.ServiceDesc for URLShortnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var URLShortnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "urlshortnerapiv1.URLShortnerService",
	HandlerType: (*URLShortnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShortURL",
			Handler:    _URLShortnerService_ShortURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "url-shortner/v1/url-shortner.proto",
}
